### ISSUE TITLE
Add a log collection script for the vDVS plugin

### ISSUE THREAD

**Issue by govint** [vmware/vsphere-storage-for-docker#1042]
Similar to how users collect a vm-support add a script that users can run and which collects at least the below logs from a docker host running the plugin.

Plugin, docker, system logs, /proc/mounts, plugin configuration, ps -ef output, docker -a, docker volume ls, admin cli ls, admin cli vm-group, ESX service logs, each in a file of its own, tar-gzipped.

comments from https://github.com/vmware/docker-volume-vsphere/issues/1407#issuecomment-308208148

We could something like what's collected for a vm-support on ESX. Every possible command is executed on the host to collect every possible data on it and thats included as part of the logs in a vm-support.

So, in case of a CI error (only), lets run thru all possible docker commands and admin CLI commands and print a log of all those command output. Like, list volumes, then inspect each volume, list containers on each test VM, list volumes, vmgroups, vms in vmgroups, in admin cli. Its not a whole lot but in an error scenario it shows up readily the state of the docker host and ESX.

**Comment by shuklanirdesh82** [comment]
this is for usability/debuggability closing this as `wontfix`
