### ISSUE TITLE
Automate the version control test with managed plugin

### ISSUE THREAD

**Issue by lipingxue** [vmware/vsphere-storage-for-docker#1059]
There are three cases need to be tested:
1. client version is older than the server version, ```docker volume create``` should fail with error message that "client version need to be upgraded".
2. client version is newer than server version, ```docker volume create``` should fail with error message that "server version need to be upgraded:.
3. client version is the same as server version, ```docker volume create``` should succeed.

Please see the manual testing in this PR #1046

**Comment by shuklanirdesh82** [comment]
#1020 managed plugin support has been added to CI (sanity check)

**Comment by shuklanirdesh82** [comment]
not a high priority.
