### ISSUE TITLE
Convert ESX service to a REST API based service

### ISSUE THREAD

**Issue by govint** [vmware/vsphere-storage-for-docker#1079]
The plugin and ESX service today talk to each other via VMCI which, while it serves the purpose of talking to the ESX service on a local node, is more a traditional sockets based approach with inherent issues. We've seen issues with doing retires, Linux kernel level driver issues, GO and C language issues that continue to plague the plugin. This alone would make this a priority to handle for the near term.

A REST based API service is way better as it allows the plugin to talk to the ESX service without worrying over command retries, errno detection and handling and even over the wire data marshall/unmarshall.

REST based API also allows easy interfacing with multiple ESX service instances across ESX hosts, if thats needed. Migration of volumes is one possibility where peer ESX instances may want to interface to handle volume transfers between remote datastores. Easily extendable to add more functionality.

The ESX service may be able to support disk ops directly to vSphere storage objects - snap'ing objects for example. Direct data get/put to objects is one more.

**Comment by govint** [comment]
The admin CLI too can become a guest OS side entity - allowing users full mgmt capability of the service. Similar to what other plugin vendors offer.

**Comment by pdhamdhere** [comment]
Moving to REST doesn't really make client-server communication fault tolerant. Both, vSocket or REST API, are wrapper over N/W and have to deal with communication errors. 
Additionally REST would require client to talk to Server over TCP and has to deal with access & security issues which is no less painful than VMCI errors.
I didn't understand how REST APIs make cross-esx communication easier unless you have centralized component like vCenter. 

Regarding Admin CLI, I think we discussed this before as well. Admin CLI is an "Administrative" operation and there is no reason to make it available in guest without any authentication and authorization. Once we move to esxcli (#623), powercli, VI Admins can remotely administer docker volumes.

It may be difficult to discuss arch proposal like this over git issue. If you feel strongly about this, I would suggest to put together rough proposal and discuss over phone. Makes sense?

**Comment by pdhamdhere** [comment]
I noticed you have tagged for v1 GA milestone. Do you really think this is a GA blocker? This doesn't impact user experience or stability of product by any means. I would tag it for Future as of now and we can pull it in after going over proposal.

**Comment by govint** [comment]
Agree this isn't a GA issue. I'll make a proposal later.

**Comment by msterin** [comment]
Can we have one "shopping basket" Issue for post-GA discussions and just add there ideas/suggestions for now. 
This will prevent us from getting distracted and spending time now on something that has no impact on V1 GA, as well as it will minimize the scary number of open issues :-)
