### ISSUE TITLE
implement discovery for multi-node ESX vm-groups (fka tenants) support

### ISSUE THREAD

**Issue by msterin** [vmware/vsphere-storage-for-docker#1086]
Related to #1032 

With PR #1065 admin would have to manually configure each ESX node by manually ssh-ing to each of them and running admin `config init`. We need to allow the admin to do all from a single node. 

This issue is to track implementation of auto-discovery for configuration 
(note: see internal Confluence site for notes on the subject) 
[ ] On CLI, allow a set of ESX to auto-discover (e.g. allowed_ESX=* or list of IPs) 
[ ] On vmdk_ops, we support NotConfigured  -> MultiNode by periodically checking for new DB on shared datastores, and if 1 (and only one) shows up there, checking for current ESX being allowed, and then changing local config to use shared DB . Note - this is a one way street. Once defined, it becomes a single point of failure, and the only way to remove it is to run local CLI on each ESX impacted.
[ ] for Stateless (PXE-boot) ESXi we can use this to enable the Config DB (MultiNode) mode 

//CC @shaominchen @pdhamdhere @govint

**Comment by tusharnt** [comment]
Cross ESX multi tenancy feature is currently experimental feature so moving this to future.

**Comment by shuklanirdesh82** [comment]
based on https://github.com/vmware/vsphere-storage-for-docker/issues/1086#issuecomment-317892309 .. adding `wontfix` kw.
