### ISSUE TITLE
Refactoring get_volumes implementation in vmdk_utils

### ISSUE THREAD

**Issue by pshahzeb** [vmware/vsphere-storage-for-docker#1121]
This function still assumes that there can be a case where volumes may not reside in tenant directories but directly inside "dockvols" directory. This doesn't told true in current state and we can get ride of that code (specifically "if not tenantre " check). Doing this also requires rewriting a couple test cases in vmdkops_admin_test.

Also, the entire get_volumes need a refactoring which will make it simple. Suggestions from #1114

**Comment by shuklanirdesh82** [comment]
refactoring task; adding `wontfix`
