### ISSUE TITLE
Rework python code layout and function names to comply with module and naming convesions

### ISSUE THREAD

**Issue by msterin** [vmware/vsphere-storage-for-docker#1153]
.py code is not properly modularized - it's layout in src/ is different from what it ends up on ESX whihc makes it hard to lint and debug, the naming convensions for intenral/external functions  are not followed, 
__all__  and __init__.py are not defined for modules. All this defeats many lint and IDE code control support, We need to fix it eventually

**Comment by govint** [comment]
Setting future milestone.

**Comment by shuklanirdesh82** [comment]
refactoring task; adding `wontfix`

/CC @tusharnt
