### ISSUE TITLE
stop building/publishing DEB/RPM to complete our move to managed plugins

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1166]
related to #1051 and refer https://github.com/vmware/docker-volume-vsphere/issues/1051#issuecomment-294250409 for more information.

Our release note also claims about removal of DEB/RPM.

As of 0.13 vDVS release, we gave heads up about limited support for DEB/RPMs and going to be deprecated soon, so raising this issue to keep track of the work.

- [ ] remove make targets to build DEB/RPMs
- [ ] stop generating during regular builds 
- [ ] remove entry from `.drone.yml` for github releases hook while tagging the master
- [ ] update README.md/Contributing.md/Installation Instruction after dropping build support

/CC @msterin @tusharnt

**Comment by govint** [comment]
Setting to rafiki to either close or resolve. Only the managed plugin is supported anymore for docker.

**Comment by govint** [comment]
We have had at least one customer who wanted an RPM for the plugin. Lets fix this as its already documented that the managed plugin is the only format supported.

**Comment by tusharnt** [comment]
@ashahi1 to add a test for validating RPM/DEB based install.

**Comment by shuklanirdesh82** [comment]
As discussed offline with @tusharnt, we have decided to stop publishing DEB/RPM and leave the code as it is. If there is a need, one can build on their own.
