### ISSUE TITLE
Add CI testbed information at CONTRIBUTING.md

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1170]
Update CONTRIBUTING.md to reflect current CI vm with docker version, ESX version, GOS etc.

- [ ] publish CI matrix

**Comment by shaominchen** [comment]
We will update this after the testbed infrastructure is finalized to accommodate all test scenarios.

**Comment by shaominchen** [comment]
Document should be finalized regarding CI testbed configuration.
