### ISSUE TITLE
Avoid code duplication

### ISSUE THREAD

**Issue by lipingxue** [vmware/vsphere-storage-for-docker#1187]
In vmdkops_admin.py,  the following code snippet is repeated several times:
```
# Check the existing config mode
    with auth_data.AuthorizationDataManager() as auth:
        try:
            auth.connect()
            info = auth.get_info()
            mode = auth.mode # for usage outside of the 'with'
        except auth_data.DbAccessError as ex:
            return err_out(str(ex))
```

Need to abstract the above code snippet into a separate function.

**Comment by tusharnt** [comment]
Cross ESX multi tenancy feature is currently experimental so putting this on the back burner for now.

**Comment by shuklanirdesh82** [comment]
code refactoring, adding `wontfix`
