### ISSUE TITLE
deploy-all target should take more than one ESX and more than 2 VMS

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1274]
Currently our deployment script installs VIB only to one ESX and plugin on 2 VMs. Our deployment target should takes care multiple input.

**Comment by shaominchen** [comment]
Some test scenarios are being commented out due to testbed limitation. We need to collect all the detailed requirements here and decide what's exactly needs to be done.

**Comment by shaominchen** [comment]
We need to first figure out how many test scenarios are being blocked by this. If there are a lot, we should mark this as mustfix, as it impacts code coverage.
