### ISSUE TITLE
[E2E] Need a general poller util to avoid blind sleeping in the tests

### ISSUE THREAD

**Issue by shaominchen** [vmware/vsphere-storage-for-docker#1301]
In some e2e tests, we have to wait until some time-consuming operations (such as VM power on/off, Kill Docker Container, etc.) to complete. Currently we are just blindly sleeping for some fixed time, and then verify the expected result. This is not only inefficient, but also unstable.

It's inefficient because we have to set a time limit big enough to make sure the operation is completed, and even if the operation completes in a shorter time, we are still waiting the fixed time, which is just a waste.

It's unstable because in some cases (depending on machine, OS, or any other conditions) the operations may not complete in the fixed time, then the test case will still fail.

To solve this issue, we need to introduce a general util function to do polling. This util function should accept a function, expected result, maximum time limit as parameters. This way we can avoid blind waiting here and there, which will significantly slow down the whole test suite. The basic polling logic will be like this:

for {
    result := time_consuming_func()
    if result == "expected_result" {
        return true;
    }

    if timePassed > timeLimit {
        return false;
    }
    sleep(short_interval)
}

**Comment by shuklanirdesh82** [comment]
@shaominchen  I am parking this with you .. let's see we need it as part of 0.16 or we may defer it for  v1GA.

**Comment by shaominchen** [comment]
This will improve the total running time of e2e test, but not a must fix for Kubecon.
