### ISSUE TITLE
Automate testbed to have nested VMs and vm into resource pool

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1316]
Reference: https://github.com/vmware/docker-volume-vsphere/issues/747#issuecomment-284125817

Testbed automation.
- [ ] Need to check whether we can extend testbed deployment script which creates atleast one vm into nested vm folder and at-least one vm into resource pool

**Comment by shaominchen** [comment]
Improving code coverage - marking as mustfix for Kubecon.

**Comment by shuklanirdesh82** [comment]
discussed with @shaominchen and decided that it is not a mustfix and we will revisit in the future.
