### ISSUE TITLE
Prepare a runlist for nested VM/resouce-pool VM testbed

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1317]
Reference #747 

Tasks:

- [ ] Create a runlist to add planned tests from #747
- [ ]  Tests should be run in automated fashion bi-weekly/per-release

**Comment by shaominchen** [comment]
Improving code coverage - marking as mustfix for Kubecon.

**Comment by shuklanirdesh82** [comment]
discussed with @shaominchen and decided that it is not a mustfix and we will revisit in the future.
