### ISSUE TITLE
[E2E] Automate swarm test - start service without restart_policy

### ISSUE THREAD

**Issue by shaominchen** [vmware/vsphere-storage-for-docker#1333]
[To be discussed]

Have  1 primary and 1 secondary node:
1. Run a service with 1 instance for it. Swarm will run it on the primary (say),
2. Kill that VM, swarm manager should be taken over on the secondary and the service should be restarted.
3. In the mean time the volumes mounted on the killed VM should have been detached on the primary host.
4. Verify that the services can be successfully restarted.

**Comment by govint** [comment]
@shaominchen, setting release to rafiki, please evaluate if this can be done for spiderman.

**Comment by shaominchen** [comment]
The test scenario is not finalized yet and needs further discussion. Not a mustfix for now.
