### ISSUE TITLE
[E2E]Automate swarm test - failover

### ISSUE THREAD

**Issue by shaominchen** [vmware/vsphere-storage-for-docker#1335]
[To be discussed]

Swarm and failover:
   a. Create Swarm cluster with at least 1 master and 2 worker nodes
   b. Deploy http://vmware.github.io/docker-volume-vsphere/documentation/docker-stacks.html Change DB constraint to "node.role == worker"
  c. Force poweroff worker1 and wait for all services to restart
  d. Power on worker1
  e. Force poweroff worker2 and wait for all services to restart
  f. Power on worker2
  g. Remove stack
  h. Make sure no disks are attached to any VM

**Comment by shaominchen** [comment]
Moving #1378 into simba, move this one out.

**Comment by govint** [comment]
@shaominchen, setting this issue to rafiki to start with, can you update if this will make it or re-assign to spiderman.

**Comment by shaominchen** [comment]
The test scenario is not finalized yet and needs further discussion to clarify. Not a mustfix for now.
