### ISSUE TITLE
[E2E] Automate P2 Tenancy Test case - Replace VM from tenant

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#1338]
- [ ] Tenant replace with a VM which already exists in it
- [ ] Tenant replace with a VM which doesn’t exist
- [ ] Tenant replace with a VM which is already a part of another tenant

**Comment by shaominchen** [comment]
Seems like basic test scenario that can improve code coverage - marking as mustfix for Kubecon.

**Comment by shaominchen** [comment]
As discussed offline - we agree that P2 tests should not be mustfix.
