### ISSUE TITLE
[E2E] Automate P2 Tenancy Test case - Remove vm from a tenant

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#1339]
- [ ] Remove VM added to a tenant
- [ ] Remove a VM from a tenant which was never added to it

**Comment by shaominchen** [comment]
Seems like basic test scenario that can improve code coverage - marking as mustfix for Kubecon.

**Comment by shaominchen** [comment]
As discussed offline - we agree that P2 tests should not be mustfix
