### ISSUE TITLE
Need to add alerts to be shown on UI

### ISSUE THREAD

**Issue by msterin** [vmware/vsphere-storage-for-docker#1363]
When vDVS is running into serious issues (e.g. BrokenLink config mode, etc...) we need to inform the admin that an manual recovery is required. The mechanism for that is Alerts which are shown for a proper ESX host on VC UI. 

This issue is to do the following: 
- [ ] Enumerate the key events we need to show as alerts
- [ ] implement (there is a related vMOMI API so it should be fairly straighforward)

**Comment by shaominchen** [comment]
VC event integration - marking as mustfix for Kubecon.
