### ISSUE TITLE
Need to add e2e tests to verify vDVS Authorization Config DB state machine

### ISSUE THREAD

**Issue by shaominchen** [vmware/vsphere-storage-for-docker#1456]
Please refer to this document: https://github.com/vmware/docker-volume-vsphere/blob/b3249234271f1f568aaa97542b8ce8c4611b3a44/docs/misc/ConfigDB_state.md

We need to add a group of e2e test cases to verify the Config DB state machine.

**Comment by shaominchen** [comment]
Improving code coverage.

**Comment by shuklanirdesh82** [comment]
@shaominchen this is related with CEMT? do we still want to have `mustfix` kw?

/CC @tusharnt

**Comment by shaominchen** [comment]
Yes, as we agreed, removing mustfix for CEMT related issues.
