### ISSUE TITLE
[E2E] Moving a VM across tenants and validates volume accessibility

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#1491]
Need to add additional steps to the test: https://github.com/vmware/docker-volume-vsphere/blob/master/tests/e2e/basic_test.go#L159

Steps to be added: 
1. Remove vm from vmgroup.
2. Verify volumes of default vmgroup are again accessible.
3. Verify volumes of original vmgroup are not accessible.

**Comment by shaominchen** [comment]
Seems basic testing scenario that should be added to improve code coverage.

**Comment by shuklanirdesh82** [comment]
this is related with cross-esx multi-tenancy (`moving vm across tenants`) --> it shouldn't be mustfix.
