### ISSUE TITLE
[E2E] Refactor code to get multiple volume properties with invoking one call to ssh.InvokeCommand

### ISSUE THREAD

**Issue by lipingxue** [vmware/vsphere-storage-for-docker#1496]
In current test automation code, if we want to get a specific property of a list of volumes,  we make multiple calls to "ssh.InvokeCommand". Instead, we should refactor the code to make one call to "ssh.InvokeCommand" to get property of all volumes in one shot and then store them in a map which can be used later.
For example,  in the following code snippet from ```TestVmgroupRemoveWithRemoveVol```, we
call ```GetVMGroupForVolume```  in a loop to get the vmgroup associated with a volume for a list of two volumes. 
```
volumeList := []string{vg.volName1, vg.volName2}
	for _, volume := range volumeList {
		out, err = verification.GetVMGroupForVolume(vg.config.EsxHost, volume)
		log.Println("GetVMGroupForVolume return out[%s] err[%s] for volume %s", out, err, volume)
		c.Assert(err.Error(), Equals, "exit status 1", Commentf("volume %s should be removed", volume))
	}
```

**Comment by shuklanirdesh82** [comment]
Keeping it P1 .. we should not abuse ssh call.
