### ISSUE TITLE
[Test automation] Need refactoring code in "vmgroups_test.go"

### ISSUE THREAD

**Issue by lipingxue** [vmware/vsphere-storage-for-docker#1497]
In the current code of "vmgroups_test.go", we pre-create the test configuration(two vmgroups) in the ```SetUpSuite``` function. This test configuration will be shard by all the tests in this suite.
This is not right since each test may have different requirement for the test configuration.
We need to refactor the code to let each test create its own configuration.

**Comment by govint** [comment]
Ok, I did write this and it keeps the individual tests simpler without the need to create a new/separate configuration for each test. If multiple tests can use a single set up that should be fine vs. refactoring these tests.
