### ISSUE TITLE
Need test binary to enable verbose mode of gocheck

### ISSUE THREAD

**Issue by pshahzeb** [vmware/vsphere-storage-for-docker#1509]
To have better time reporting of our e2e tests, we need to enable verbose mode (done through -check.v flag).
It provides following advantages - 

- [ ] Provides detailed information for each test suite - time required and individual test suite pass or fail.
- [ ] Prints overall summary at the end of test-all target.

CC @shuklanirdesh82

**Comment by shuklanirdesh82** [comment]
will be addressed as part of Jenkins CI task. closing this as wontfix.
