### ISSUE TITLE
[E2E]Not able to see access rights for default vmgroup

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1520]
Steps mentioned in  #1396

**Comment by lipingxue** [comment]
I discussed it with Sam, since the product behavior  regarding the default vmgroup is still under discussion and we have not reached the conclusion yet (see #1397 ), so move this issue to future.

**Comment by msterin** [comment]
Not sure why the original issue was closed. At any rate, the original one says
```
Tried to see access rights for _DEFAULT vmgroup
Failed with error:
Please init configuration with 'vmdkops_admin.py config init' before changing it.
```

The behavior is correct. When config is not inited, there is no concept of vmgroups and no access control.
We should change a message to something like the one below. No other code changes IMO
```
Configuration is not initialized.
No vmgroups  are defined, no quotas or access control is supported. 
If you are trying to change it, first initialized configuration with  'vmdkops_admin.py config init'
```

**Comment by shaominchen** [comment]
At least we should have consistent behavior for showing vmgroup and access rights. Marking as mustfix.

**Comment by shuklanirdesh82** [comment]
as discussed during the meeting, the workflow would be verified manually and during `flash` sprint automation will be added.

@ashahi1 Let's verify manually and add automation test during `Flash` sprint
