### ISSUE TITLE
Create a util to get a bunch of volume properties

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#1527]
- [ ] Create an util verification.CheckVolume() which will check against a bunch of volume properties.   https://github.com/vmware/docker-volume-vsphere/pull/1381#discussion_r123506846

**Comment by msterin** [comment]
is it a request to wrap 'docker inspect' (CLI or API)  in some test util ?

**Comment by ashahi1** [comment]
@msterin Yes, plan is to write a test util for ene-to-end tests to get all volume properties
