### ISSUE TITLE
Refactor fs module

### ISSUE THREAD

**Issue by venilnoronha** [vmware/vsphere-storage-for-docker#1538]
Currently, the `fs` module is exported as a bunch of `func`s, so the following changes are suggested.

1. Create an `interface` with the necessary `func`s and have them implemented under a `struct`. [[discussion](https://github.com/vmware/docker-volume-vsphere/pull/1504#discussion_r125215070)]
2. Create a `func` to handle the default `fstype` selection for volume requests. [[discussion](https://github.com/vmware/docker-volume-vsphere/pull/1504#discussion_r125209436)]

See #1504 for more information.

**Comment by shuklanirdesh82** [comment]
refactoring task; adding `wontfix`
