### ISSUE TITLE
E2E tests require root as username for VMs

### ISSUE THREAD

**Issue by luomiao** [vmware/vsphere-storage-for-docker#1571]
The current E2E tests assume that the username is always root for the testbed VMs.
However this is not necessarily true.
A user should be able to have other usernames on the testbed VMs with enough permission to run the e2e tests.

Maybe introducing more env variables for users to provide username/password of testbed VMs?

**Comment by govint** [comment]
As long as the setup is done to allow commands to be executed on other guests and the ESX the tests should work as is as a non-root user. Root access isn't needed to run the tests.

**Comment by luomiao** [comment]
but the InvokeCommand function inside ssh.go is hard-coded to use root as username.

**Comment by govint** [comment]
Ok, it doesn't need that, should be changed to get user name and use that. But then there has to be that user on each docker host. Root is just easy to use as its there on every node.
