### ISSUE TITLE
Blog for multi-tenancy feature

### ISSUE THREAD

**Issue by lipingxue** [vmware/vsphere-storage-for-docker#1592]
This blog will talk about multi-tenancy feature on single ESX host.

**Comment by shaominchen** [comment]
We already have the blog (draft version): https://confluence.eng.vmware.com/display/CNAS/Multi-tenancy+Feature+in+vSphere+Docker+Volume+Service

Since CEMT is an experimental feature and still subject to change, this should not be a must fix for Kubecon release.
