### ISSUE TITLE
Make vDVS plugin code compliant with golang standards and code style guidance

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1593]
Please refer for more information: https://github.com/vmware/docker-volume-vsphere/pull/1574 Raising this issue to make existing files compliance the golang convention.

Reference: https://github.com/vmware/docker-volume-vsphere/pull/1574#issuecomment-315170940

Lots of code is not compliant with standards and code style guidance.

The golang.org says in https://blog.golang.org/package-names 
```
 Good package names are short and clear. They are lower case, with no under_scores or mixedCaps. They are often simple nouns, such as:

    time (provides functionality for measuring and displaying time)
    list (implements a doubly linked list)
    http (provides HTTP client and server implementations)

The style of names typical of another language might not be idiomatic in a Go program. Here are two examples of names that might be good style in other languages but do not fit well in Go:

    computeServiceClient
    priority_queue

A Go package may export several types and functions. For example, a compute package could export a Client type with methods for using the service as well as functions for partitioning a compute task across several clients.

Abbreviate judiciously. Package names may be abbreviated when the abbreviation is familiar to the programmer. Widely-used packages often have compressed names:

    strconv (string conversion)
    syscall (system call)
    fmt (formatted I/O)

On the other hand, if abbreviating a package name makes it ambiguous or unclear, don't do it. 
```

We should guard the new code to follow the above approach.

/cc @msterin

**Comment by shuklanirdesh82** [comment]
@tusharnt I am raising this as P0 for current sprint so it will be easier to guard new code with the proposed guideline.

**Comment by tusharnt** [comment]
No customer impact so I am pushing this past VMworld milestone.

**Comment by shuklanirdesh82** [comment]
making code compliant with golang standard so adding `mustfix` (can be discussed further while planning out kubecon release)

**Comment by shuklanirdesh82** [comment]
code refactoring so adding `wontfix`
