### ISSUE TITLE
Need Windows VM in dev environment

### ISSUE THREAD

**Issue by venilnoronha** [vmware/vsphere-storage-for-docker#1637]
Currently our dev environment supports Ubuntu VMs. With Project Skylight, VMware developers would also need a Windows VM for dev/test purposes.

/cc @shaominchen @tusharnt

**Comment by shaominchen** [comment]
Basically we need to enhance existing testbed deployment script to deploy a windows VM as well.

**Comment by shuklanirdesh82** [comment]
falls into improving dev productivity category.

**Comment by tusharnt** [comment]
Not a high priority ask.
