### ISSUE TITLE
Add test to verify docker compose file can specify volume with format "vol@datastore".

### ISSUE THREAD

**Issue by lipingxue** [vmware/vsphere-storage-for-docker#1666]
This has bee fixed through docker/cli#306, and will be available on docker 17.08.0.
Need to add test to verify this after docker 17.08.0 is available.

**Comment by shuklanirdesh82** [comment]
this is mustfix to improve test coverage.

**Comment by lipingxue** [comment]
For detailed test step, please refer to #1315 .

**Comment by tusharnt** [comment]
@ashahi1 will manually execute this test scenario for KubeCon release.
