### ISSUE TITLE
Automate managed plugin push while tagging the release

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1699]
Please refer https://github.com/vmware/docker-volume-vsphere/blob/master/CONTRIBUTING.md#publish-vdvs-managed-plugin-to-docker-store

```
Note: not automated as of 04/04/17

To push plugin image

DOCKER_HUB_REPO=vmware EXTRA_TAG= VERSION_TAG=latest make all
DOCKER_HUB_REPO=vmware EXTRA_TAG= VERSION_TAG=<version_tag> make all
```

Above steps should be automated while tagging the release.

/CC @ashahi1

**Comment by shuklanirdesh82** [comment]
release process automation mustfix.

**Comment by tusharnt** [comment]
This is contingent upon moving to 0.5 release for drone.

**Comment by shuklanirdesh82** [comment]
This is no longer valid as decided to move onto Jankins CI.
