### ISSUE TITLE
After plugin upgrade, docker has to be restarted to see all the volumes

### ISSUE THREAD

**Issue by ashahi1** [vmware/vsphere-storage-for-docker#1753]
Error: If plugin is upgraded with container running, docker volume ls does not show all volumes. Docker has to be restarted to see all volumes.

Test Steps:
```
1. Installed 0.15 vDVS plugin
2. Created two volumes.
3. Ran a container with one of the volumes mounted.
4. While container was running, uninstalled the 0.15 plugin and installed 0.16 plugin.
5. After 0.16 plugin was successfully installed, ```docker volume ls``` does not show both volumes
6. Restarted the docker and could see both the volumes but docker restart caused container to be exited.
```

Is this behavior expected? Should user be stopping a container to do plugin upgrade?

Logs have been attached at the end

---------------------------------------

Steps and their output are as follows:

1. Installed 0.15 plugin
```
root@photon-machine [ ~ ]# docker plugin install --grant-all-permissions --alias vsphere15 vmware/docker-volume-vsphere:0.15
0.15: Pulling from vmware/docker-volume-vsphere
967f49dfadaf: Download complete
Digest: sha256:64a50830c2fa9befbede6efca3f28d2e2d8b4e595703f1b5984470579656e935
Status: Downloaded newer image for vmware/docker-volume-vsphere:0.15
Installed plugin vmware/docker-volume-vsphere:0.15
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
fe44e3b62f64        vsphere15:latest    VMWare vSphere Docker Volume plugin   true
root@photon-machine [ ~ ]#
```
2. Created two volumes
```
root@photon-machine [ ~ ]# docker volume create -d vsphere15 --name TestVol15
TestVol15
root@photon-machine [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere15:latest    TestVol15@local2
root@photon-machine [ ~ ]# docker volume create -d vsphere15 --name TestVol15_XX
TestVol15_XX
```
3. Mounted one of the volumes to a container
```
root@photon-machine [ ~ ]# docker run -it --volume-driver=vsphere15:latest -v TestVol15@local2:/vol1 --name ubUpgrade ubuntu
root@459006671aa3:/# echo "Hello" >> /vol1/hello
root@459006671aa3:/# cat vol1/hello
Hello
Hello World
Hello World CAT
root@459006671aa3:/#
```
4. While container was running, uninstalled vDVS 0.15 plugin and installed 0.16 version
```
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
fe44e3b62f64        vsphere15:latest    VMWare vSphere Docker Volume plugin   true
root@photon-machine [ ~ ]# docker plugin rm -f vsphere15:latest
vsphere15:latest
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED
root@photon-machine [ ~ ]# docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest
latest: Pulling from vmware/docker-volume-vsphere
ad10a6bbce92: Download complete
Digest: sha256:feaa90e4234880fbf1669015e88cd485b2077270219ff84a730b35207bb622d4
Status: Downloaded newer image for vmware/docker-volume-vsphere:latest
Installed plugin vmware/docker-volume-vsphere:latest
```
5. Did docker volume ls but do not see all the volumes - volume that was attached is no longer shown
```
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
db4670541e9d        vsphere:latest      VMWare vSphere Docker Volume plugin   true
root@photon-machine [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      TestVol15_XX@local2
root@photon-machine [ ~ ]#
```
6. Restarted the docker and then I could see both the volumes
```
root@photon-machine [ ~ ]# systemctl restart docker
root@photon-machine [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      TestVol15@local2
vsphere:latest      TestVol15_XX@local2
```

-----------------------------------------

Logs:
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/1223818/docker-volume-vsphere.txt)
[vmdk_ops.log.1.txt](https://github.com/vmware/docker-volume-vsphere/files/1223820/vmdk_ops.log.1.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/1223819/vmdk_ops.txt)

**Comment by govint** [comment]
@ashahi1 what version of Docker is this? Because docker doesn't even allow disabling a plugin (busy error is reported) if volumes are available (in use or not) that are associated with that plugin. Doubt even rm is feasible when a volume managed by the plugin is in use. Flip side is even if all volumes are removed DOcker will still disallow disabling a plugin and needs to be restarted. Its a bug on the docker side.

**Comment by ashahi1** [comment]
> Because docker doesn't even allow disabling a plugin (busy error is reported) if volumes are available (in use or not) that are associated with that plugin. 

Usage of --force flag allows us to remove the plugin.

**Comment by govint** [comment]
As long as the plugin alias (in docker plugin install) is the same there is no issue - plugin driver upgrade scenario. Issue happens only if the alias changes - another plugin driver is registered with a different alias and tries to use the same socket. Checking how this is handled on the docker/moby side. Will update on that shortly.

**Comment by govint** [comment]
Tested with 17.07 and don't see any problem. Created a volume with one version of the driver and with a certain alias. Then ran a container with the volume. Then removed the plugin and installed a newer version with a different alias. Then stopped the container (started earlier) and created and new volume and docker is able to show both volumes.

Will verify with 17.03 again.

**Comment by govint** [comment]
@ashahi1 am not able to repro this issue at all, this is what I did:

docker plugin install --grant-all-permissions --alias vsphere15 vmware/docker-volume-vsphere:0.15
0.15: Pulling from vmware/docker-volume-vsphere
967f49dfadaf: Download complete
Digest: sha256:64a50830c2fa9befbede6efca3f28d2e2d8b4e595703f1b5984470579656e935
Status: Downloaded newer image for vmware/docker-volume-vsphere:0.15
Installed plugin vmware/docker-volume-vsphere:0.15

docker volume create -d vsphere15 upvol1
upvol1

docker run -it --rm -v upvol1:/mnt busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
9e87eff13613: Pull complete
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for busybox:latest
/ # 

docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
b401d9c62f12        vsphere15:latest    VMWare vSphere Docker Volume plugin   true

docker plugin rm -f b401d9c62f12
b401d9c62f12

docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest
latest: Pulling from vmware/docker-volume-vsphere
ad10a6bbce92: Download complete
Digest: sha256:feaa90e4234880fbf1669015e88cd485b2077270219ff84a730b35207bb622d4
Status: Downloaded newer image for vmware/docker-volume-vsphere:latest
Installed plugin vmware/docker-volume-vsphere:latest

 docker volume inspect upvol1
[]
Error: No such volume: upvol1 <---------- this is expected as the volume is matched against a driver named vsphere15. New driver won't be matched for an existing volume.

docker volume create -d vsphere upvol2
upvol2

docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      upvol1@sharedVmfs-0
vsphere:latest      upvol2@sharedVmfs-0


Pls. let me know if this sequence is what you are seeing and if the steps are matching.

**Comment by ashahi1** [comment]
@govint This issue is reproducible. I deployed a fresh setup and I cans till see this issue. I can also share the setup details with you if that helps to debug the issue.

**Comment by ashahi1** [comment]
@govint I deployed a new setup and not able to see this issue hence closing it.
