### ISSUE TITLE
Prepare videos to demonstrate vDVS features that can be uploaded on VMware youtube channel

### ISSUE THREAD

**Issue by tusharnt** [vmware/vsphere-storage-for-docker#1770]
Prepare videos to demonstrate vDVS features that can be uploaded on VMware youtube channel

cc @pdhamdhere

**Comment by shuklanirdesh82** [comment]
This is nice to have but not mustfix for kubecon release

**Comment by shuklanirdesh82** [comment]
Project Hatchway introductory video is out ---> https://www.youtube.com/watch?v=mZxQyHwAefY&t

**Comment by shuklanirdesh82** [comment]
based on https://github.com/vmware/vsphere-storage-for-docker/issues/1770#issuecomment-348672187 closing this one.
