### ISSUE TITLE
Placeholder for code changes to handle plugin upgrade for vFile

### ISSUE THREAD

**Issue by luomiao** [vmware/vsphere-storage-for-docker#1877]
Currently users need to stop the plugin on every node in a right order (worker -> manager -> leader) before re-install the plugins.
Need handle code for a hot upgrade.

**Comment by shuklanirdesh82** [comment]
`mustfix` for vFile beta release

**Comment by luomiao** [comment]
Need tests.
Create Epic for this issue.
