### ISSUE TITLE
Investigate running the plugin and ESX service on VMC version  of ESX

### ISSUE THREAD

**Issue by govint** [vmware/vsphere-storage-for-docker#1882]
This issue is to verify that the hatchway plugin is able to function on the VMC version of ESX. Specifically, the below items should be verified.

1. VMCI - does VMC support VMCI, since the ESX isn't supposed to be accessible as such, is this support present? If not then consider enabling alternate access to the ESX service (would something like #1079 help?).
1. Given users don't get to access the ESX, how are the admin CLI commands used. There is most likely no admin to run admin cli commands for the docker user. How is this supported? One way is to expand the ESX service to support the actions that are today done via the CLI.

**Comment by shuklanirdesh82** [comment]
Investigation should be `mustfix` 

/CC @tusharnt

**Comment by shuklanirdesh82** [comment]
discussed with @tusharnt and closing this as `wontfix`.
