### ISSUE TITLE
Need more testbed setups on CI ESX machine

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1899]
Currently we have only one testbed setup with the following configuration.

Testbed configuration:
**2 ESX VMs**: 6.5 & 6.0 U2 ESX
**Datastore**: 
1. VSAN & VMFS for ESX 6.5
2. VSAN & VMFS for ESX 6.0 U2

** Test VMs **
1. 4 VMS on ESX 6.5 (2 VMs on VMFS and 2 on VSAN datastore where 1 photon and 1 ubuntu each)
2. 4 VMS on ESX 6.0 (2 VMs on VMFS and 2 on VSAN datastore where 1 photon and 1 ubuntu each)

**Comment by shuklanirdesh82** [comment]
CI improvement issue: adding mustfix kw for kubecon release

**Comment by tusharnt** [comment]
Dup of #1269
