### ISSUE TITLE
Allow more than one CI builds to run

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1902]
Right now [validate-and-serialize.sh](https://github.com/vmware/docker-volume-vsphere/blob/master/misc/drone-scripts/validate-and-serialize.sh) is restricting to have only one run get going as we have only 1 testbed to run against. 

We need some changes to the above script to make PR wait time can be reduced.

Script should be configurable as per number of testbeds in place.

**Comment by shuklanirdesh82** [comment]
CI improvement: adding mustfix to improve dev productivity

**Comment by tusharnt** [comment]
This will get addressed after moving 0.5 release of drone.

**Comment by shuklanirdesh82** [comment]
closing this as wontfix as we are moving to Jenkins CI and this codeflow will be changed
