### ISSUE TITLE
[vFile test] Need to use poller instead of static wait time of 80 seconds

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/vsphere-storage-for-docker#1993]
CI link: https://ci.vmware.run/vmware/docker-volume-vsphere/1781

I am seeing 10 occurrences of `80 seconds` of wait time, could save some time through intelligent polling.
```
017/11/16 04:00:16 Wait 80 seconds for original worker to be updated
2017/11/16 04:01:36 END: VFileDemotePromoteTestSuite.TestSwarmRoleChange
```

@lipingxue I am parking with you, please reassign appropriately.

**Comment by tusharnt** [comment]
Not high priority.
