### ISSUE TITLE
VM Admission control/ compatibility checks

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/vsphere-storage-for-docker#275]
DRS or maintenance mode features can trigger live migration of VMs to Host which do not have ESX Server VIB installed. Though migrating VM won't affect running containers. Any subsequent management operations would fail in absence of ESX Server VIB.

Is there a way to add compatibility check in admission control to prevent migrating VMs consuming docker volumes to Hosts that do not have ESX Server VIB running?

**Comment by govint** [comment]
This may not be doable to include a constraint on every VM, but frankly mgmt. workflows that integrate containers into vSphere don't exist today. The ESX service VIB should really become part of the vSphere platform as a way to expose a storage provisioning interface for vSphere storage to use or its deprecated in favor of a VC based way of doing this. Precluding any compat checks. The VC way is perhaps better given it handles placement plus balancing across datastores and can be enhanced in a much better way (multi-tenancy) than having isolated per host service (which anyway works just for the host alone).

Marking for kubecon to document this requirement to have the ESX service VIB installed on all nodes used in container hosting clusters and close after that.

**Comment by shuklanirdesh82** [comment]
based on https://github.com/vmware/vsphere-storage-for-docker/issues/275#issuecomment-332740897 closing this as wontfix.
