### ISSUE TITLE
list of items - A Road to MVP (minimum viable product) 

### ISSUE THREAD

**Issue by msterin** [vmware/vsphere-storage-for-docker#3]
This issue enumerates the work we need to do before releasing MVP for native Docker VMDK Data Volume support. Please extend the list if you see something missing. 
- [x] Discuss and review/finalize plans 
  - [x] Finalize use cases/ clean up wiki / publish functional spec with use cases (depends on other items in this section)
  - [ ] \* authentication / config: How do we identity trusted VM ? What is the config format (a list of "enable" glob expressions for .vmx config or VM uuid (think about vmotion ) ? Where do we keep the info ? Do we force port_id < 1024 ?  
  - [ ] \* policy  and quotas. Do we introduce VMDK grouping for this purposes? Format? Where to keep data? 
  - [x] \* packaging - ESX side (VIB, live install/uninstall, VUM updates in cluster, watchdog, jumpstart)
  - [x] \* packaging - docker side (daemon config, minimal container with caps to run the plugin)
  - [x] \* release timing and documentation  -- what do we need? Also,  release process - legals? docs? goto market? anything else ?
  - [x] \* CI and test. (note: if needed, We can do scaffolding around cron/nimbus, and then go to drone.io)
  - [ ] \* VC story: how to get a list of all VMDKs used (or explicitly requested) by docker VMs? Size? Check for stale VMDKs (i.e. created but not used in ages) ?  Etc...
- [x] Clean up and review/fix of TODO in the code 
  - [x] \* Design and Use proper logs (ESX and linux), drop prints
  - [x] Add timing metrics for ops to logs for t-shooting
  - [x] \* Handle time outs in calls to FindChild() and friends – it’s normal if we need to reconnect to hostd as session may time out. 
  - [ ] \* Discuss and Add support needed for K8S: "no formatting" option (or explicit formatting type request), location. 
  - [x] \* Add support for VSAN/Vvol. Currently mkfs uses <file>-flat.vmdk. Need to check disk.backing and choose the backend appropriately (note: not needed when there is no FS formatting)
  - [x]  \* Add proper PVSCSI controller/disks create() automation. Currently we rely on pre-configured VM, this is unacceptable and already mentioned in "installation issues".
  - [ ]  Make VMDK requests non-blocking: split Go/C API into SendRequest and GetReply (blocking), have ESX code spawn threads tor this and have Go use goroutines. 
  - [x] Drop exec(“mount”) from Go - use syscall.mount().  Drop exec("vmkfstools") from python, use VirtualDiskManager
  - [x] \* Add internal volume tracking per Docker spec - e.g. no need to attach stuff already attached by another container. Detach also happens on refcount only.
  - [x] \* Other TODOs - signal handling, track volumes UUIDs for more reliable delete (currently full file name is the ID of the disk to delete), clean up sizes (drop fixed size) in C/vSocket code.
- [x] \* Design and implement build ,CI & testing set
  - [ x] Separate components (see "installation issues" Issue docker-vmdk-plugin#1). Needs to have 
    - Go module (vmware/docker-vmdk-plugin/vmdkops) - uses 'go get' and 'go build' (in container)
    - ESX build (vmware/docker-vmdk-plugin/vmdkops-esxsrv) - uses vibauthor container 
    - Docker plugin (vmware/docker-vmdk-plugin/plugin) - uses 'go' in container
    - container used for build only 
  - [ x] Build: Make all container-driven, per above.
  - [x] DeployToESX for CI: assuming packaging (above) is done and ESX is deployed, govmomi or pyvmomi code to deployVIB, deploy docker VM (a few flavors) with plugin, run basic tests
  - [x] CI: GitHub, CI and test infra - deploy ESX (numbus? drone.io?) , run deployToEsx 
  - [x] \* unit tests. (_test.go) – includes a vmdkops replacemend module to do local "vmdk" (falloc , format, loopback mount) - that will test the rest of the logic. 
  - [ x] use Photon  for build and Plugin container (low priority) - already supported
  - [x] \* Busy work: Support Python3 and keep Python2 (since newer ESX support only Python 3). 
- [ ] \* Docker PR - Missing functionality (independent from MVP)
  - [ ] \* 'docker volume inspect' is missing metadata passed with -o. So if we pass size or policy via -o, there is nothing about this in inspect
  - [ ] \* 'docker volume ls' does not allow to enumerated driver-specific volumes which were not "created" In the current docker daemon. So there is no way to see what's already there for VMDKs.
  - [x ] **Docker 1.10 seems to be addressing these already**, see  "https://github.com/docker/docker/pull/16534 -  Move responsibility of ls/inspect to volume driver #16534 "   -(comment: not true. Still missing a way to pass our metadata)
  - [x] \* It also adds support for anon. volumes (https://github.com/docker/docker/pull/19190) , we need to  support / test it

(note: \* before the text indicates that there is a separate PR opened for the item

**Comment by shaominchen** [comment]
Liping will go through the list first, and then we should call a meeting to finalize the list.
