### ISSUE TITLE
List volumes created by the current VM

### ISSUE THREAD

**Issue by msterin** [vmware/vsphere-storage-for-docker#64]
It is important to give a dev a way to clean up stale volumes.
At this moment it is not clear if adding "Author" to metadata to keep track which VM created is easy (we'd need to check DiskLib sidecars and use the private API), but we need to support cleanup in any case.

We cannot fully delegate clean up to admin as even stale volumes may be needed to a dev.

So we will keep a dvolplug/vmdkops.log file (much as vmware.log is kept by VMX) and we will use this log to find out what was created by which VM.
From Docker point of view, we need something like 

 Docker volume ls --driver=vmdk -c

To request a list of items created by current VM

**Comment by govint** [comment]
Setting future milestone.
