### ISSUE TITLE
Include coverage reports to be part of PR.

### ISSUE THREAD

**Issue by kerneltime** [vmware/vsphere-storage-for-docker#670]
As part of each PR, a coverage report should be generated to help detect untested code.

**Comment by kerneltime** [comment]
We should integrate with coverage.vmware.run

**Comment by kerneltime** [comment]
This has been planned for next release

**Comment by tusharnt** [comment]
@ashahi1 What's the update on this?

**Comment by shuklanirdesh82** [comment]
we're moving to difference CI model and will be taken care as part of the activity.
