### ISSUE TITLE
Move docker api usage to the new import

### ISSUE THREAD

**Issue by kerneltime** [vmware/vsphere-storage-for-docker#815]
The old engine-api import is deprecated. 
More into @ https://github.com/docker/engine-api
We use these for tests.

**Comment by shuklanirdesh82** [comment]
Two tests need to be enhanced

1. https://github.com/vmware/docker-volume-vsphere/blob/c95d9a3775b4ba804f63de8c8140722df23e2030/vmdk_plugin/sanity_test.go#L28
2. https://github.com/vmware/docker-volume-vsphere/blob/0241cae8b7c091a9510754bc5d544530c74cdfeb/vmdk_plugin/utils/refcount/refcnt.go#L82

**Comment by shaominchen** [comment]
Not an urgent issue - moving to P2.

**Comment by govint** [comment]
Pulling to spiderman, at the least this should be resolved/dropped by spiderman.

**Comment by shuklanirdesh82** [comment]
will be taken care as part of #2000
