### ISSUE TITLE
Need kill switch for vmodl support

### ISSUE THREAD

**Issue by msterin** [vmware/vsphere-storage-for-docker#943]
We need to have kill switch for VMODL support, and for *not* recycling vsanmgmgt svc on our svc start. This will prevent unneeded impact on VSAN unless VMODL need to be turned on. 

I suggest doing it via installing the vmodl files somewhere else  and modifying vmdk-opsd -to  NOT recycle vsanmgmt svc by default, and adding  `vmdk-opsd vmodlon` and `vmodloff` manipulate the vmodl py files location and vsanmgmtd restart

Putting in 1.12 for discussion 

//CC @pdhamdhere @shaominchen

**Comment by shaominchen** [comment]
@msterin I agree with you. Will address this in the next release.

**Comment by shaominchen** [comment]
Hi @msterin Why did we close this issue? The PR #975 just turned off VMODL install, but we still need to introduce a kill switch so that we can toggle on/off the VMODL support. Correct?

**Comment by msterin** [comment]
github auto closed this when #975 merged. Yes, we need the kill switch post-GA. Reopening
